Repository KaidanIM/Kaidan, pull requests merged in 2018-03, with the labels that each got.

#206 android: Fix icon sizes and sort commands correctly
  utils/build-android-deps.sh
Labels: build system & build scripts

#205 Fix lag when changing chat
  src/ClientThread.cpp
  src/ClientThread.h
  src/Kaidan.cpp
  src/Kaidan.h
  src/MessageHandler.cpp
  src/MessageHandler.h
  src/MessageModel.cpp
  src/MessageModel.h
Labels: back-end, bug fix

#208 travis-ci: Restructure build scripts and clean up
  .travis.yml
  utils/travis-build.sh
  utils/travis-dependencies.sh
  utils/travis/build.sh
  utils/travis/common.sh
  utils/travis/dependencies.sh
Labels: build system & scripts

#150 Ubuntu Touch packaging
  .gitignore
  .travis.yml
  CMakeLists.txt
  README.md
  clickable.json
  cmake/FindGloox.cmake
  misc/ubuntu-touch/apparmor.json
  misc/ubuntu-touch/kaidan.desktop
  misc/ubuntu-touch/manifest.json.in
  src/Globals.h
  src/main.cpp
  utils/build-click.sh
  utils/travis/build.sh
  utils/travis/common.sh
  utils/travis/dependencies.sh
Labels: packaging, work in progress

#210 travis-ci: Use Qt 5.10
  utils/travis/common.sh
Labels: build system & scripts

#211 Fix release build TLS connection bug!
  src/ServiceDiscoveryManager.cpp
Labels: back-end, bug fix

#218 Add different connection error messages
  src/qml/LoginPage.qml
Labels: user interface

#222 use QApplication when qwidgets found
  CMakeLists.txt
  src/main.cpp
Labels: user interface

#221 RosterPage: Fix names are displayed too short
  src/qml/elements/RosterListItem.qml
Labels: bug fix, roster / contacts, user interface

#223 Spelling: because not → as a result of not
  i18n/base.ts
  i18n/de.ts
  i18n/es.ts
  i18n/fr.ts
  i18n/ja.ts
  i18n/ms.ts
  i18n/nb.ts
  i18n/nl.ts
  i18n/pt.ts
  i18n/ru.ts
  src/Kaidan.cpp
Labels: l10n/i18n
