Repository KaidanIM/Kaidan, pull requests merged in 2018-04, with the labels that each got.

#224 Roster: Don't automatically accept subscription requests
  src/RosterUpdater.cpp
Labels: back-end, bug fix, roster / contacts

#230 Fix VCards of newly added contacts are not loaded
  src/RosterUpdater.cpp
Labels: back-end, bug fix

#227 AddContactSheet: Add optional message for subscription request
  src/ClientThread.h
  src/Kaidan.cpp
  src/Kaidan.h
  src/RosterManager.cpp
  src/RosterManager.h
  src/qml/elements/RosterAddContactSheet.qml
Labels: back-end, user interface

#238 Implement XEP-0300: Use of Cryptographic Hash Functions in XMPP
  Kaidan.pro
  src/CMakeLists.txt
  src/gloox-extensions/gloox-extensions.h
  src/gloox-extensions/hash.cpp
  src/gloox-extensions/hash.h
Labels: back-end

#239 Reimplement file stanza extension from XEP-0234: Jingle File Upload
  Kaidan.pro
  src/CMakeLists.txt
  src/gloox-extensions/gloox-extensions.h
  src/gloox-extensions/jinglefile.cpp
  src/gloox-extensions/jinglefile.h
Labels: back-end

#241 Implement XEP-0385: Stateless Inline Media Sharing (SIMS)
  src/gloox-extensions/gloox-extensions.h
  src/gloox-extensions/sims.cpp
  src/gloox-extensions/sims.h
Labels: back-end, media

#242 Display a help text if no contact is selected
  i18n/base.ts
  i18n/de.ts
  i18n/es.ts
  i18n/fr.ts
  i18n/ja.ts
  i18n/ms.ts
  i18n/nb.ts
  i18n/nl.ts
  i18n/pt.ts
  i18n/ru.ts
  kaidan_qml.qrc
  src/qml/EmptyChatPage.qml
  src/qml/main.qml
Labels: chat, trivial, user interface
