Repository KaidanIM/Kaidan, pull requests merged in 2018-02, with the labels that each got.

#182 Fix font sizing
  src/qml/elements/ChatMessage.qml
  src/qml/elements/RosterListItem.qml
Labels: bug fix, user interface

#186 CMakeLists.txt: Clean up and remove old code
  CMakeLists.txt
Labels: build system, trivial

#188 Use ccache on travis-ci
  .travis.yml
  utils/build-appimage.sh
  utils/travis-build.sh
Labels: build system

#189 Automatically reconnect 5s after disconnection
  src/ClientWorker.cpp
  src/ClientWorker.h
Labels: back-end

#192 Fix not connecting on the first time
  src/ClientThread.cpp
  src/ClientThread.h
  src/ClientWorker.cpp
  src/ClientWorker.h
Labels: back-end, bug fix

#194 RosterPage: Indicate if connecting in title
  src/qml/RosterPage.qml
Labels: user interface

#195 Add XEP-0352: Client State Indication
  src/ClientThread.cpp
  src/ClientThread.h
  src/ClientWorker.cpp
  src/ClientWorker.h
  src/Kaidan.cpp
  src/Kaidan.h
  src/main.cpp
Labels: back-end

#196 Use passive notifications when online actions fail
  src/Kaidan.cpp
  src/Kaidan.h
  src/qml/main.qml
Labels: user interface

#199 Encode passwords in base64 to make them not directly visible
  src/ClientWorker.cpp
  src/Kaidan.cpp
Labels: back-end

#202 i18n: Add missing qm files to QRC file
  i18n/0_i18n.qrc
Labels: bug fix

#191 Render logos from source
  misc/android/res/mipmap-hdpi/icon.png
  misc/android/res/mipmap-hdpi/logo.png
  misc/android/res/mipmap-ldpi/icon.png
  misc/android/res/mipmap-ldpi/logo.png
  misc/android/res/mipmap-mdpi/icon.png
  misc/android/res/mipmap-mdpi/logo.png
  misc/android/res/mipmap-xhdpi/icon.png
  misc/android/res/mipmap-xhdpi/logo.png
  misc/android/res/mipmap-xxhdpi/icon.png
  misc/android/res/mipmap-xxhdpi/logo.png
  misc/android/res/mipmap-xxxhdpi/icon.png
  misc/android/res/mipmap-xxxhdpi/logo.png
  utils/build-android-deps.sh
Labels: build system

#204 RosterPage: Display if offline in title
  src/qml/RosterPage.qml
Labels: user interface
