Repository KaidanIM/Kaidan, pull requests merged in 2018-05, with the labels that each got.

#245 travis: Fix that apt cache is empty at begin
  utils/travis/dependencies.sh
Labels: continous integration

#246 ubuntu-touch: update apparmor policy version
  misc/ubuntu-touch/apparmor.json
Labels: Ubuntu Touch

#244 MessageHandler: No notifications for carbon messages
  src/ClientThread.cpp
  src/MessageHandler.cpp
  src/MessageHandler.h
Labels: back-end, bug fix

#251 MessageHandler: Fix timezone bug of timestamps, Clean up
  src/MessageHandler.cpp
  src/MessageModel.cpp
Labels: back-end, bug fix, chat

#249 Redesign login page
  src/qml/LoginPage.qml
Labels: bug fix, user interface

#255 Fix resource binding and append four random chars
  src/ClientThread.cpp
  src/ClientThread.h
Labels: back-end, bug fix

#254 avatars: Optimize vCard fetchment, Use SHA1 hashes locally
  src/AvatarFileStorage.cpp
  src/AvatarFileStorage.h
  src/RosterUpdater.cpp
  src/VCardManager.cpp
Labels: back-end, bug fix

#257 ubuntu-touch: Remove dependency of QQC2
  utils/build-click.sh
Labels: Ubuntu Touch, build system & scripts
